on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: moajo/terraform-metadata@main
        with:
          metadata_path: test/sample.json
      - run: echo "$DATA"
